export default {
  LAST_OPENED: 'lastOpened',
  IS_FAVORITE: 'isFavorite',
  ENTER_KEY: 'Enter',
  ESCAPE_KEY: 'Escape',
  SPACE_KEY: ' ',
  F_KEY: 'f',
  I_KEY: 'i',
  FAVORITE_STATE: {
    FAVORITE: 'favorite',
    NOT_FAVORITE: 'not-favorite',
    PARTIALLY_FAVORITE: 'partially-favorite',
  },
  FAVORITE_COLOR: 'var(--yellow-43)',
  PRODUCT_TYPE: 'product',
  FOCUS_SEARCH_BAR_EVENT: 'focus:searchBar',
  VIEW_TYPE: {
    TILE: 'tile',
    LIST: 'list',
  },
  GROUPPING_TYPE: {
    CATEGORY: 'category',
    ALPHABETICAL: 'alphabetical',
  },
  PRODUCT_NAME: 'productName',
  ALL_APPS: 'all',
  EUISDK_TYPE: 'euisdk',
  NAME_RANK: 5,
  TAGS_RANK: 3,
  SECONDARY_INFO_RANK: 2,
  DESC_RANK: 1,
  LANDING_CARD_COUNT: 8,
  SHOW_FAVORITES_ONLY: 'favorites',
  COLLAPSED_CARD_COUNT: 4,
  EXTERNAL_TYPE: 'external',
};
